#!/bin/bash

# This assumes that the symfony command will be in the $PATH; if in vendor/bin/ it will be

## Description: Run Symfony Console CLI (console) command inside the web container
## Usage: console [args]
## Example: "ddev console cache:clear"
## ExecRaw: true

if [ ! -f /usr/bin/symfony ]; then
  echo '/usr/bin/symfony does not exist.'
  exit 1
fi

if [ ! -f /var/www/html/symfony/bin/console ]; then
  echo 'console does not exist in the Symfony project root directory.'
  exit 1
fi

cd symfony
symfony console "$@"
